### PR TITLE
return if newItem is null

### PR DESCRIPTION
**Pull request by DrBot7**
Fixes the issue described at https://www.spigotmc.org/threads/simple-rename.111439/page-7#post-3868856

### CODE REVIEW

**Comment by LittleBigBug** [comment]
Here's a build if you need it in the meantime, https://github.com/LittleBigBug/SimpleRename/releases/tag/13.6-unofficial

**Comment by galaipa** [comment]
Thank you very much both for your work! :D

**Comment by galaipa** [comment]
It still needs some more investigation, but I will post an update ASAP.

The reason I think it needs further investigation is that according to the [documentation](https://papermc.io/javadocs/paper/1.16/org/bukkit/event/inventory/InventoryInteractEvent.html#getResult--) the getResult method of an InventoryInteractEvent can never return a null value. So either the docs are outdated, or there is a bug somewhere. I can't reproduce it using regular Spigot, so I think it's specific to PaperSpigot.

I will keep you posted!

**Comment by galaipa** [comment]
Sorry, I was checking the wrong javadoc, so your commit is good enough! [This](https://papermc.io/javadocs/paper/1.16/org/bukkit/event/inventory/PrepareAnvilEvent.html#getResult--) is the right one.

Thank you again!

**Pull request merged**
